PREFIX realfagstermer: <http://data.ub.uio.no/realfagstermer/>
PREFIX mads: <http://www.loc.gov/mads/rdf/v1#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ubo: <http://data.ub.uio.no/onto#>

SELECT *
WHERE {
  GRAPH <http://data.ub.uio.no/realfagstermer> {
    ?complexConcept skos:prefLabel ?label ;
                    ubo:component ?component .
    ?component skos:prefLabel ?componentLabel .
  }
  FILTER (LANG(?label) = "nb")
  FILTER (LANG(?componentLabel) = "nb")
}
ORDER BY ?concept
LIMIT 100
